### ISSUE TITLE
No effect when installed on VS 2017 Ent with Visual Assist disabled and later uninstalled

### ISSUE THREAD

**Issue by yurikus** [hicknhack-software/semantic-colorizer#10]
Hi, 

I wanted to see if I can improve syntax highlighting by using your tool instead of VA's one, which is lacking now. Installed extension, restarted VS, no effect. Disabled VA, no effect. uninstalled VA, restarted VS, no effect. I can help you diagnose if you'd like.

To clarify - I even changed colors to see if that would trigger it to work. All I get is native VS highlighting - gray mess.

Cheers,
Yuriy

**Comment by arBmind** [comment]
First keep in mind - Semantic Colorizer works for Roslyn Languages only (C# and VBA). When I used Visual Assist, I used it for C++.

Second: Can you try my settings... [arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip](https://github.com/hicknhack-software/semantic-colorizer/files/763058/arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip) Simply extract and import them.

They should work best for the dark theme.

**Comment by yurikus** [comment]
I was trying it on C# and VB code. I just use VA out of 16 year old habit for shortcuts and colors. Will try your theme.

UPDATE: Looked at your .vssettings file:
- interesting extension - Viasfora
- What extensions are these names from: CppGlobalVariableSemanticTokenFormat, "delegate name", "enum name", "module name", "struct name" "type parameter name" ?

UPDATE 2: I think I know what the problem is - extension doesn't create its custom "colorizing names" (not sure how you call these below) when it's installed:

    s.semantic-colorizer.field
    s.semantic-colorizer.enum-field
    s.semantic-colorizer.extension-method
    s.semantic-colorizer.static-method
    s.semantic-colorizer.normal-method
    s.semantic-colorizer.constructor
    s.semantic-colorizer.parameter
    s.semantic-colorizer.namespace
    s.semantic-colorizer.property
    s.semantic-colorizer.local
    s.semantic-colorizer.type-normal

I uninstalled SC, dumped Fonts-And-Colors settings, then installed it again, dumped again. No difference

**Comment by yurikus** [comment]
Making this a new comment. I massaged the vssettings file you linked in the message above to not mess up my own settings, imported it, and it works.

**Comment by arBmind** [comment]
I am glad that it works for you now.
Some guesses... It seems that uninstalling the plugin will not make Visual Studio forget your settings. These settings are not affected by installing / uninstalling plugins. When the plugin is initially loaded it will/should create these settings.

It's possible that this part is broken. I'm quite certain that I would not recognize it, because it keeps working for me. I will try to think about a way to debug this, without destroying my setup here.
