### ISSUE TITLE
Please add support for highlighting events in C# code

### ISSUE THREAD

**Issue by Ming-Sizung** [hicknhack-software/semantic-colorizer#11]
Thanks again for this amazing extension. It works absolutely perfect ;)

However, it does not highlight `event`s in C# code. Would you please add support for it?

Sample code:
```csharp
class Test
{
    // TestEvent should be able to be highlighted
    event Action TestEvent;
}
```

**Comment by arBmind** [comment]
Version 1.3.x has this built in.
