### ISSUE TITLE
Setting "Identifier" color in Color Theme Editor for VS2017 breaks SemanticColorizer

### ISSUE THREAD

**Issue by r-tanner-f** [hicknhack-software/semantic-colorizer#14]
Had some trouble getting the SemanticColorizer to work in my custom VS2017 theme. I tracked it down to the "Identifier" color being set within the Color Theme Editor. If "Identifier" is set to Automatic then everything is OK, but setting a specific color prevents any other colors from being set using SemanticColorizer.

Not sure if it's something that can be worked around, or is worth working around as I'm not entirely sure what the point of the "Identifier" color is, but I thought it was worth bringing up in case anyone else runs in to this problem.

**Comment by arBmind** [comment]
Thank you @r-tanner-f for figuring this out. I gave up on this already. VS2017 behaves very strangely with syntax highlighting. Plugins register new types for the color and font dialog. But I have not found any description of what overwrites what. All semantic types are a specialization to `identifier`.

I will do some more experiments on my side. Maybe we can give a better how to use this plugin description.

**Comment by arBmind** [comment]
The new 1.3.0 release also fixes some odd issues with the ordering.

I hope this fixes this issue as well.
