### ISSUE TITLE
Doesn't work with Visual Studio v15.7.0

### ISSUE THREAD

**Issue by iMobCoding** [hicknhack-software/semantic-colorizer#16]
Like title says, just installed v15.7.0 update and semantic doesn't work anymore...

**Comment by arBmind** [comment]
Yes, I see the bug… but I have no idea what is wrong. The code compiles fine as before.

Has anyone a hint, what was changed in 15.7 - related to Roslyn?

**Comment by iMobCoding** [comment]
I don't have an idea, but tested similar Roslyn addons and it seems none of them work anymore

**Comment by GitHubFocus** [comment]
I find the namespace and the constructor are still colorized, so other don't work.

**Comment by iMobCoding** [comment]
Found on the net, that actual problems started between v15.7 preview 2 and preview 3. On preview 2, everything still worked, on preview 3 was broken. 

So maybe that can help you. Here are list of changes between previews:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

**Comment by cdytoby** [comment]
I have the same issue, I noticed that "normal method" is colored on private constructor, but not on normal method like `private void MyMethod()`

Namespace seems still work.

**Comment by cdytoby** [comment]
Updated to 15.7.1, issue remains.

And I noticed another thing: local function in c# 7.0 is correctly colorized.

**Comment by loftum** [comment]
It might be because most `ClassifiedSpan`s are filtered out.

On https://github.com/hicknhack-software/semantic-colorizer/blob/develop/SemanticColorizer/SemanticColorizer.cs#L197
try removing `where comparer.Compare(cs.ClassificationType, "identifier") == 0`, and rather deal with ClassifiedSpan.ClassificationType in the switch.

**Comment by iMobCoding** [comment]
@loftum is right
@arBmind Please check the fix from another similar addon:
https://github.com/GeorgeAlexandria/CoCo/commit/c1d9dd1225dd0d64b3588f43eb5ce4da0c6f4afc

**Comment by arBmind** [comment]
The new release 1.3.0 fixes the issues with VS 2017 15.7.

Thank you all @crmagicxxx @loftum and @cdytoby for the good analysis.
@Liminiens pull request was merged by hand.
