### ISSUE TITLE
Colorizing settings priority

### ISSUE THREAD

**Issue by Liminiens** [hicknhack-software/semantic-colorizer#18]
While it's allowed to change color of the struct/classes/enums/interfaces/delegates/type parameters via extension, it looks like that VS will always give it's own settings ("User Types - ..." sections in Options-> Fonts and Colors) a higher priority, unless the color is set to Automatic (?). 

If it's true, i think it should be mentioned somewhere in the readme.

**Comment by arBmind** [comment]
That should not be true. There is the `[Order(After = …` attribute in `EditorFormat.cs`. We may have to tune them a bit more. A more specialized Classification should override broader ones. Unfortunately this will take a bit of fiddling.

**Comment by Liminiens** [comment]
@arBmind so the `Order(After = "identifier")` trick does the overriding of default setting, am I right?

**Comment by arBmind** [comment]
I removed all redundant Formats in the `develop` branch.

and changed the readme.
