### ISSUE TITLE
Support for VS 2019

### ISSUE THREAD

**Issue by clairernovotny** [hicknhack-software/semantic-colorizer#28]
There are a couple of minor updates needed for the VSIXManifest to support VS 2019:

https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

No other changes necessary.

**Comment by ncksol** [comment]
#29 this seems to be working for me

**Comment by arBmind** [comment]
VS2019 should work with the latest version now!

**Comment by arBmind** [comment]
I close this. If you find issues with VS 2019 please open a new issue.
