### ISSUE TITLE
Roll back?

### ISSUE THREAD

**Issue by stesvis** [hicknhack-software/semantic-colorizer#30]
Hello is it possible to roll back?
I had this extension on "Automatically update", and from today almost all my color settings are gone.
Yesterday everything was perfect.

Thanks

**Comment by arBmind** [comment]
Hmm… strange… I am not aware of such a feature.

**Comment by stesvis** [comment]
@arBmind is it possible to undo the latest change included in yesterdays's update?
In **Tools->Fonts and Colors** all the Semantic items are gone now, I lost all my color customizations.

![image](https://user-images.githubusercontent.com/6062684/49674924-cbd66600-fa30-11e8-9768-6f2276b22286.png)

**Comment by arBmind** [comment]
That's strange! For me it still works.
What Version of Visual Studio are you using?
Are you sure the extension SemanticColorizer is activated? 
Are there any errors logged?

**Comment by stesvis** [comment]
I looked at your commit and i saw the comment about Vs 2019 so i downloaded it.
I am using VS 2017.
It worked well in VS 2019 but other extensions don't work so i can't use it.

But when i went back to VS 2017  the colors were back, so I'm sure that installing VS 2019 fixed whatever was missing.

Now i use VS 2017 buy i have to leave 2019 installed.

**Comment by arBmind** [comment]
Ok, I am glad it works now for you!

It still seems strange. I do not have VS2019 and it still works as before.

Nevertheless, I will close this issue as it seems to work for you!

**Comment by zbernhardtme** [comment]
I would ask that this issue be re-opened.  It happened to me today too.  

It auto-updated, I restarted, my code shows default colors, I check Tools > Options > Environment > Fonts and Colors, and there are no options that start with "Semantic".

VS 2017 Community Edition on Windows 10 x64 v1803

**Comment by stesvis** [comment]
Glad I wasn't delusional! :)

**Comment by zbernhardtme** [comment]
My last post didn't say 'please' and 'thank you'.  I appreciate what you do, so thank you!

I was able to get my colors back by _disabling_ and re-enabling and restarting several times.  So, my issue is fixed.  I don't know what the fix was though.
