### ISSUE TITLE
Can't make it work!

### ISSUE THREAD

**Issue by LeoGigliotti** [hicknhack-software/semantic-colorizer#4]
Since the new version (12/16/2016) SemanticColorizer stopped working. I can't find it under "Fonts and Colors" tab, nor in any other window. It shows as enabled in the "Extensions and Updates" window, but is it? Maybe my configs are wrong?

![image](https://cloud.githubusercontent.com/assets/7051172/21274554/f6ba526e-c3af-11e6-90f9-19e8944bd976.png)

**Comment by arBmind** [comment]
Approved. Stopped working for VS2015 see #5
