### ISSUE TITLE
1.2 doesn't work on VS2015 update 3

### ISSUE THREAD

**Issue by mkova** [hicknhack-software/semantic-colorizer#5]
I just noticed it doesn't work. I see that 1.2 came yesterday, it must auto updated and stopped working.

**Comment by mkova** [comment]
confirmed, I built 1.1.4 and it works again

**Comment by arBmind** [comment]
I can confirm that VS2015 does not seem to work. I have no clue why, I will try to check this.

**Comment by arBmind** [comment]
I have fixed the issue by redoing the conversion process for VS2017. This time with less trial and error.

Works now with both versions.
