### ISSUE TITLE
Colour Scheme

### ISSUE THREAD

**Issue by nykwil** [hicknhack-software/semantic-colorizer#7]
I downloaded it and it installed properly but my default colour scheme is very different from the example. Fields are solid red and namespaces are solid green as an example.  I'm okay with it not installing properly, I have other plugins and other colour customization so I'm less worried about it installing with the right colours but it would be good if there was some schemes that you can download and apply. Like a dark and light theme for example.

**Comment by arBmind** [comment]
Hey @nykwil, good idea. Sorry that the default colors are a bit awful. I don't know how to place defaults for different color schemes.
I thought everybody who bothers to install such a plugin is willing to configure it properly. And just needs some verification that the plugin indeed works as promoted.
I guess I was wrong.

It would be great if we had some valid schemes. I only have a dark scheme and no idea how to extract it into something redistributable.

Can someone provide a good light theme?
And a hint how these are distributed best?

**Comment by nykwil** [comment]
Tools -> Import and Export Settings... starts a import/export wizard for creating partial settings files. There's even online databases for vssettings files (like https://studiostyl.es/). Just need people to submit schemes. I'm really bad at selecting colours, just knowing colours that don't work.

**Comment by arBmind** [comment]
@nykwil thank you for your useful hints. I have exported my settings:

[arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip](https://github.com/hicknhack-software/semantic-colorizer/files/692095/arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip)

studiostyl.es only allows to create styles using their website, which does not support styles for plugins. So we cannot upload it there.

@all - Does these kind of exported style work for you?
