### ISSUE TITLE
Changing colors

### ISSUE THREAD

**Issue by Mikaka27** [hicknhack-software/semantic-colorizer#8]
Hi, sorry for posting this here, but I cannot find information how to change the colors in this extension.
I also noticed that colors are different in the extension and in the advertising screenshot (I kinda like ones from the screenshot better).
Can I somehow change them to match ones in the screenshot?

**Comment by arBmind** [comment]
Hi, you change settings in the normal color settings dialog of visual studio. If you scroll through it, you will see some semantic colors there.

I could not find a good location to upload the demo settings. So I attached them here for now.
If you are keen enough to try them, please report the results.

[arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip](https://github.com/hicknhack-software/semantic-colorizer/files/763058/arBmind_InputMono_Viasfora_SemanticColorizer_Dark.zip)

**Comment by HamidMosalla** [comment]
@arBmind  Thanks for the great extension, I'd suggest you mention that colors can be customized through normal visual studio dialog with some screenshots, cause it might not be immediately obvious to some people, including someone like me, Thanks.

**Comment by arBmind** [comment]
Thanks for the hint. I added both my settings and the hint how to change the colors to the readme and plugin description.
